In [1]:
import pandas as pd
import numpy as np

In [2]:
# Question 1: Version of Pandas

pd.__version__

'1.4.4'

In [3]:
df = pd.read_csv('raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv')

In [4]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
# Question 2: Number of columns in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [7]:
# Question 3: Select columns with missing data

df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [8]:
# Question 4: Number of unique values in the 'ocean_proximity' column

df['ocean_proximity'].nunique()

5

In [9]:
# Question 5: Average value of the 'median_house_value' for the houses near the bay. 
# mean = 259212.311790

df[df['ocean_proximity'] == 'NEAR BAY'].describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [10]:
# Question 6: Has the mean value changed after filling missing values?

# 6.1 - Calculate the average
df['total_bedrooms'].mean()

537.8705525375618

In [11]:
# 6.2

df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [12]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [13]:
# 6.3

df['total_bedrooms'].mean()

537.8705525375639

In [14]:
# Question 7
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [15]:
df[['housing_median_age', 'total_rooms', 'total_bedrooms']][df['ocean_proximity'] == 'ISLAND'].head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [25]:
x = df[['housing_median_age', 'total_rooms', 'total_bedrooms']][df['ocean_proximity'] == 'ISLAND']

In [68]:
xt = x.transpose()
xt

8314    8315    8316   8317   8318
housing_median_age    27.0    52.0    52.0   52.0   29.0
total_rooms         1675.0  2359.0  2127.0  996.0  716.0
total_bedrooms       521.0   591.0   512.0  264.0  214.0

In [70]:
print(x.shape, xt.shape)

(5, 3) (3, 5)


In [99]:
xtx = xt.dot(x)

In [100]:
xtx

housing_median_age  total_rooms  total_bedrooms
housing_median_age              9682.0     351053.0         91357.0
total_rooms                   351053.0   14399307.0       3772036.0
total_bedrooms                 91357.0    3772036.0        998358.0

In [101]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [80]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [102]:
print(xtx_inv.shape, xt.shape, y.shape)

(3, 3) (3, 5) (5,)


In [108]:
w = xtx_inv.dot(xt).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])